apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  # namespace: {{ .Values.namespace }}
  #(CDLTLL) Another option based on the namespaces provided in the release:
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "articlesrailsapi.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
    spec:
      containers:
      - name: {{ .Values.container.name }}
        image: "{{ .Values.container.image }}"
        imagePullPolicy: {{ .Values.container.imagePullPolicy }}
        env:
        - name: DBHOST
          value: {{ .Values.env.DBHOST }}
        - name: DBUSER
          value: {{ .Values.env.DBUSER }}
        - name: DBPASS
          value: {{ .Values.env.DBPASS }}
        - name: SERVICE_HOST_NAME
          value: {{ .Values.env.SERVICE_HOST_NAME }}
        ports:
        - containerPort: {{ .Values.container.port }}