apiVersion: apps/v1
kind: Deployment
metadata:
  name: articlesrailsapi-deployment
  namespace: ruby-rails-apis-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: articlesrailsapi-app
  template:
    metadata:
      labels:
        app: articlesrailsapi-app
    spec:
      containers:
      - name: articlesrailsapi-container
        image: rubyonrailspocs/articlesrailsapi
        imagePullPolicy: Always
        env:
        - name: DBHOST
          value: postgresql
        - name: DBUSER
          value: postgres
        - name: DBPASS
          value: password
        - name: SERVICE_HOST_NAME
          value: articlesrailsapi
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: articlesrailsapi
  namespace: ruby-rails-apis-poc
spec:
  type: NodePort
  selector:
    app: articlesrailsapi-app
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30002
