apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendwebapp-deployment
  namespace: ruby-rails-apis-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontendwebapp-app
  template:
    metadata:
      labels:
        app: frontendwebapp-app
    spec:
      containers:
       - name: frontendwebapp-container
         image: rubyonrailspocs/frontendwebapp:latest
         imagePullPolicy: Always
         ports:
         - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: frontendwebapp
  namespace: ruby-rails-apis-poc
spec:
  type: NodePort
  selector:
    app: frontendwebapp-app
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001