apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name }}
  # namespace: {{ .Values.namespace }}
  #(CDLTLL) Another option based on the namespaces provided in the release:
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.app }}
spec:
  accessModes:
    {{- toYaml .Values.pvc.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}